# Generated by Django 4.0.7 on 2023-03-30 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0002_alter_auto_id_alter_make_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'nickname should be long enough')])),
                ('mileage', models.PositiveIntegerField()),
                ('comments', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Enter a make (eg. Maruti)', max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Make must be long enough')]),
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
        migrations.AddField(
            model_name='autos',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.make'),
        ),
    ]
