# Generated by Django 4.0.7 on 2023-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0003_autos_alter_make_name_delete_auto_autos_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='make',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
