# Generated by Django 4.0.7 on 2023-03-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='foods',
        ),
        migrations.AlterField(
            model_name='cat',
            name='weigth',
            field=models.FloatField(),
        ),
    ]
