# Generated by Django 4.0.7 on 2023-03-31 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_remove_cat_foods_alter_cat_weigth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Breed must be greather than 1 character')]),
        ),
        migrations.AlterField(
            model_name='cat',
            name='nickname',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Breed must be greather than 1 character')]),
        ),
    ]
