# Generated by Django 4.0.7 on 2023-03-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_rename_weigth_cat_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='foods',
            field=models.CharField(default='fish', max_length=300),
        ),
    ]
